name: .NET Core

on:
  push:
    branches: [ master, issue/NuPkg-Exes ]
  pull_request:
    branches: [ master ]

env:
  versionSemVer: "0.1.0"
  versionSuffixRoot: "ci"
  buildNumber: ${{ github.run_number }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Clean Distribution
      run: rm -Rf ./distribution/
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore --version-suffix ${{ env.versionSemVer }}-${{ env.versionSuffixRoot }}-${{ env.buildNumber }} 
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack /p:PackageVersion=${{ env.versionSemVer }}-${{ env.versionSuffixRoot }}-${{ env.buildNumber }}
    - name: Push Library NuPkg
      run: dotnet nuget push ./**/Atlassian-Authentication-Helper*.*.nupkg --api-key ${{ secrets.MYGET_ITOFINITY_APIKEY }} --source https://www.myget.org/F/itofinity/api/v2/package
    - name: Publish Portable
      run: dotnet publish -c release -o ./distribution/portable/release 
    - name: Publish OSX
      run: dotnet publish -r osx-x64 -c release -o ./distribution/osx-x64/release /p:PublishSingleFile=true /p:PublishTrimmed=true
    - name: Publish Windows
      run: dotnet publish -r win-x64 -c release -o ./distribution/win-x64/release /p:PublishSingleFile=true /p:PublishTrimmed=true
    - name: Publish Linux
      run: dotnet publish -r linux-x64 -c release -o ./distribution/linux-x64/release /p:PublishSingleFile=true /p:PublishTrimmed=true
    - name: Pack Exes
      run: dotnet pack /p:PackageVersion=${{ env.versionSemVer }}-${{ env.versionSuffixRoot }}-${{ env.buildNumber }} /p:PackExe=True
    - name: Push Exes NuPkg
      run: dotnet nuget push ./**/Atlassian-Authentication-Helper-Executables*.*.nupkg --api-key ${{ secrets.MYGET_ITOFINITY_APIKEY }} --source https://www.myget.org/F/itofinity/api/v2/package
    - name: Upload Library Nupkg
      uses: actions/upload-artifact@v2-preview 
      with:
        name: Atlassian-Authentication-Helper.${{ env.versionSemVer }}-${{ env.versionSuffixRoot }}-${{ env.buildNumber }}.nupkg.zip
        path: ./**/Atlassian-Authentication-Helper*.*.nupkg
    - name: Upload Exes Nupkg
      uses: actions/upload-artifact@v2-preview 
      with:
        name: Atlassian-Authentication-Helper-Executables.${{ env.versionSemVer }}-${{ env.versionSuffixRoot }}-${{ env.buildNumber }}.nupkg.zip
        path: ./**/Atlassian-Authentication-Helper-Executables*.*.nupkg
    - name: Upload Portable Artifact
      uses: actions/upload-artifact@v2-preview 
      with:
        name: Atlassian-Authentication-Helper.${{ env.versionSemVer }}-${{ env.versionSuffixRoot }}-${{ env.buildNumber }}.exe.osx-x64.zip
        path: ./distribution/portable/release
    - name: Upload OSX Artifact
      uses: actions/upload-artifact@v2-preview 
      with:
        name: Atlassian-Authentication-Helper.${{ env.versionSemVer }}-${{ env.versionSuffixRoot }}-${{ env.buildNumber }}.exe.osx-x64.zip
        path: ./distribution/osx-x64/release/atlassian-authentication-helper
    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v2-preview 
      with:
        name: Atlassian-Authentication-Helper.${{ env.versionSemVer }}-${{ env.versionSuffixRoot }}-${{ env.buildNumber }}.exe.win-x64.zip
        path: ./distribution/win-x64/release/atlassian-authentication-helper.exe
    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v2-preview 
      with:
        name: Atlassian-Authentication-Helper.${{ env.versionSemVer }}-${{ env.versionSuffixRoot }}-${{ env.buildNumber }}.exe.linux-x64.zip
        path: ./distribution/linux-x64/release/atlassian-authentication-helper
    - name: Release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v${{ env.versionSemVer }}-${{ env.versionSuffixRoot }}-${{ env.buildNumber }}
        name: Release v${{ env.versionSemVer }}-${{ env.versionSuffixRoot }}-${{ env.buildNumber }}
        body: >
          CI created release  
        gzip: folders
        prerelease: true
        files: >
          Atlassian-Authentication-Helper-Portable:./distribution/portable/release
          Atlassian-Authentication-Helper-Windows:./distribution/win-x64/release/
          Atlassian-Authentication-Helper-Linux:./distribution/linux-x64/release/
          Atlassian-Authentication-Helper-Osx:./distribution/osx-x64/release/
          license:LICENSE
